import { existsSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { CATALOGS } from '../src/data/catalogs';
import catalogFiles from '../src/data/catalog-files.json';
import { DIST, docFor } from './helpers/dist';

const ARCHIVE = fileURLToPath(new URL('../archive/catalogs', import.meta.url));
const PRODUCTS = fileURLToPath(new URL('../src/content/products', import.meta.url));

/** Every product slug, read from the collection so this list cannot go stale. */
const PRODUCT_SLUGS = readdirSync(PRODUCTS)
  .filter((f) => f.endsWith('.md'))
  .map((f) => f.replace(/\.md$/, ''));

describe('catalog delivery', () => {
  // public/catalogs/ is generated by the prebuild step and gitignored. If that step
  // is skipped the page still renders and every download link 404s, which is worse
  // than the dead text it replaced. Fail loudly instead.
  it('serves every catalog from dist, at full size', () => {
    for (const catalog of CATALOGS) {
      const served = join(DIST, 'catalogs', catalog.file);
      expect(existsSync(served), `${catalog.file} was never copied into dist`).toBe(true);
      expect(statSync(served).size).toBe(statSync(join(ARCHIVE, catalog.file)).size);
    }
  });

  it('records a byte size that matches the file on disk', () => {
    for (const catalog of CATALOGS) {
      expect(
        (catalogFiles as Record<string, { bytes: number }>)[catalog.file]?.bytes,
        `${catalog.file} size has drifted — re-run scripts/sync-catalogs.mjs`,
      ).toBe(statSync(join(ARCHIVE, catalog.file)).size);
    }
  });

  it('lists exactly the six catalogs the old site offered', () => {
    expect(CATALOGS).toHaveLength(6);
  });
});

describe('downloads page', () => {
  it('generates the route with a single h1 and its canonical', () => {
    const doc = docFor('downloads/index.html');
    expect(doc.querySelectorAll('h1')).toHaveLength(1);
    expect(doc.querySelector('link[rel="canonical"]')?.getAttribute('href'))
      .toBe('https://litex.com.tw/downloads/');
  });

  it('links every catalog', () => {
    const hrefs = [...docFor('downloads/index.html').querySelectorAll('main a[href$=".pdf"]')]
      .map((a) => a.getAttribute('href'));
    for (const catalog of CATALOGS) {
      expect(hrefs, `${catalog.file} is not linked`).toContain(`/catalogs/${catalog.file}`);
    }
  });

  // A buyer on a trade-show wifi connection deciding whether to tap a 6 MB download
  // needs to know it is 6 MB before tapping it.
  it('states size and page count for every catalog before the click', () => {
    const doc = docFor('downloads/index.html');
    for (const catalog of CATALOGS) {
      const row = [...doc.querySelectorAll('[data-catalog]')]
        .find((el) => el.getAttribute('data-catalog') === catalog.file);
      expect(row, `${catalog.file} has no entry`).toBeTruthy();
      const text = row?.textContent ?? '';
      expect(text, `${catalog.file} does not state its size`).toMatch(/\d+(\.\d+)?\s*(KB|MB)/);
      expect(text, `${catalog.file} does not state its page count`).toContain('pages');
    }
  });

  it('describes each catalog rather than repeating its filename', () => {
    for (const catalog of CATALOGS) {
      expect(catalog.description.length, `${catalog.file} description is too thin`)
        .toBeGreaterThan(60);
      expect(catalog.description).not.toContain('.pdf');
    }
  });

  it('says how old the catalogs are, once, plainly', () => {
    const text = docFor('downloads/index.html').body.textContent ?? '';
    expect(text).toContain('2018');
  });

  it('is reachable from the primary navigation', () => {
    const hrefs = [...docFor('index.html').querySelectorAll('nav[aria-label="Primary"] a')]
      .map((a) => a.getAttribute('href'));
    expect(hrefs).toContain('/downloads/');
  });
});

describe('product pages link their catalog', () => {
  it('turns catalogPdf into a real download instead of dead text', () => {
    const doc = docFor('products/rfid-textile-tape/index.html');
    const link = doc.querySelector('a[href="/catalogs/2018-rfid-textile-tape.pdf"]');
    expect(link, 'the RFID product page still prints its catalog as plain text').toBeTruthy();
  });

  it('never links a catalog that is not served', () => {
    for (const slug of PRODUCT_SLUGS) {
      const doc = docFor(`products/${slug}/index.html`);
      for (const a of [...doc.querySelectorAll('a[href^="/catalogs/"]')]) {
        const href = a.getAttribute('href') ?? '';
        expect(existsSync(join(DIST, href.replace(/^\//, ''))), `${slug} → ${href}`).toBe(true);
      }
    }
  });
});
